### ISSUE TITLE
Проблема с шаблоном

### ISSUE THREAD

**Issue by awant13** [nickdsl/sevpn_zabbix#1]
Привет!

Скачал твой шаблон для SE VPN

Возникла проблема 

У пользователей SE трафик по нулям и стоит дата последнего логина последнего пользователя в массиве.

![изображение](https://user-images.githubusercontent.com/95469324/144568419-87fedee1-9611-4ea3-ac33-d48562c5cf01.png)

Через тест элементов данных значения есть.

Система 

Zabbix 5.0.15
Debian 10

**Comment by nickdsl** [comment]
Добрый день. Спасибо за фидбэк. Приятно, что труды интересны кому то ещё.
Сейчас посмотрю как оно у меня работает.

пт, 3 дек. 2021 г., 11:15 awant13 ***@***.***>:

**Comment by nickdsl** [comment]
Вспомнил, кажется был такой косяк, да. Но, скорее всего, это rest api может
криво отдавать данные. Т.е. скрипт честно получает нули.
Мне такое помнится.

Чтобы это проверить надо скопировать скрипт, запускать руками с параметрами
как в заббиксе. А еще лучше дебаг включить.
Но я помню что скрипт писал по принципу копипасты, и, скорее всего, если бы
у меня в методах была ошибка, то не работало бы много чего, а не только
метрики юзеров. =(

Но это не 100%. я проверю, но позже

**Comment by nickdsl** [comment]
Я так и не проверил 🤣

**Comment by nickdsl** [comment]
> Привет!
> 
> Скачал твой шаблон для SE VPN
> 
> Возникла проблема 
> 
> У пользователей SE трафик по нулям и стоит дата последнего логина последнего пользователя в массиве.
> 
> 
> ![изображение](https://user-images.githubusercontent.com/95469324/144568419-87fedee1-9611-4ea3-ac33-d48562c5cf01.png)
> 
> Через тест элементов данных значения есть.
> 
> 
> 
> Система 
> 
> Zabbix 5.0.15
> Debian 10 
> 

Если ты тут, то можешь ответить актуально ли тебе ещё это.
Я даже готов глянуть. Очень много времени прошло. Мне даже как то неудобно. Пообещал и не сделал.

**Comment by nickdsl** [comment]
![users_stats](https://github.com/nickdsl/sevpn_zabbix/assets/25919416/e7e3baa9-af31-4362-96e6-82dec279f2e8)
У меня со статой все норм, кстати, я зарелизил новую версию мониторинга.
