### ISSUE TITLE
Ошибка File "/etc/zabbix/scripts/sevpn.py", line 690, in <module>

### ISSUE THREAD

**Issue by zakharov69** [nickdsl/sevpn_zabbix#2]
Preprocessing failed for: Traceback (most recent call last):. File "/etc/zabbix/scripts/sevpn.py", line 690, in <module>. ...
1. Failed: cannot extract value from json by path "$['result']['Send.UnicastCount_u64']": invalid object format, expected opening character '{' or '[' at: 'Traceback (most recent call last):
File "/etc/zabbix/scripts/sevpn.py", line 690, in <module>
print(eval(METHOD))
File "<string>", line 1, in <module>
File "/etc/zabbix/scripts/s

**Comment by zakharov69** [comment]
_root@vpn:/etc/zabbix/scripts# zabbix_agentd -t sevpn[hub.discovery]
sevpn[hub.discovery]                          [t|Traceback (most recent call last):
  File "/etc/zabbix/scripts/sevpn.py", line 690, in <module>
    print(eval(METHOD))
  File "<string>", line 1, in <module>
  File "/etc/zabbix/scripts/sevpn.py", line 224, in hub_discovery
    fn_result = json.loads(hub_list())
  File "/etc/zabbix/scripts/sevpn.py", line 215, in hub_list
    fn_result = do_request(fn_method, fn_params)
  File "/etc/zabbix/scripts/sevpn.py", line 92, in do_request
    return json.loads(response.text)
  File "/usr/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)]_

**Comment by nickdsl** [comment]
Sevpn version ?
Python version ?
Operating system ?

**Comment by nickdsl** [comment]
> _root@vpn:/etc/zabbix/scripts# zabbix_agentd -t sevpn[hub.discovery] sevpn[hub.discovery] [t|Traceback (most recent call last): File "/etc/zabbix/scripts/sevpn.py", line 690, in print(eval(METHOD)) File "", line 1, in File "/etc/zabbix/scripts/sevpn.py", line 224, in hub_discovery fn_result = json.loads(hub_list()) File "/etc/zabbix/scripts/sevpn.py", line 215, in hub_list fn_result = do_request(fn_method, fn_params) File "/etc/zabbix/scripts/sevpn.py", line 92, in do_request return json.loads(response.text) File "/usr/lib/python3.9/json/**init**.py", line 346, in loads return _default_decoder.decode(s) File "/usr/lib/python3.9/json/decoder.py", line 337, in decode obj, end = self.raw_decode(s, idx=_w(s, 0).end()) File "/usr/lib/python3.9/json/decoder.py", line 355, in raw_decode raise JSONDecodeError("Expecting value", s, err.value) from None json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)]_

Sevpn version?
python version?
os version ? (distribution)

**Comment by zakharov69** [comment]
Версии такие:

root@vpn:/etc/zabbix/scripts# python3 --version
Python 3.9.2

root@vpn:/etc/zabbix/scripts# lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 11 (bullseye)
Release:        11
Codename:       bullseye

root@vpn:/etc/zabbix/scripts# /usr/local/vpnserver/vpncmd
vpncmd command - SoftEther VPN Command Line Management Utility
SoftEther VPN Command Line Management Utility (vpncmd command)
Version 4.43 Build 9799   (English)
Compiled 2023/08/31 10:50:49 by buildsan at crosswin with OpenSSL 3.0.9

**Comment by nickdsl** [comment]
> Версии такие:
> 
> root@vpn:/etc/zabbix/scripts# python3 --version
> Python 3.9.2
> 
> root@vpn:/etc/zabbix/scripts# lsb_release -a
> No LSB modules are available.
> Distributor ID: Debian
> Description:    Debian GNU/Linux 11 (bullseye)
> Release:        11
> Codename:       bullseye
> 
> root@vpn:/etc/zabbix/scripts# /usr/local/vpnserver/vpncmd
> vpncmd command - SoftEther VPN Command Line Management Utility
> SoftEther VPN Command Line Management Utility (vpncmd command)
> Version 4.43 Build 9799   (English)
> Compiled 2023/08/31 10:50:49 by buildsan at crosswin with OpenSSL 3.0.9
> 

спасибо, попробую воспроизвести у себя

**Comment by zakharov69** [comment]
> > Версии такие:
> > root@vpn:/etc/zabbix/scripts# python3 --version
> > Python 3.9.2
> > root@vpn:/etc/zabbix/scripts# lsb_release -a
> > No LSB modules are available.
> > Distributor ID: Debian
> > Description:    Debian GNU/Linux 11 (bullseye)
> > Release:        11
> > Codename:       bullseye
> > root@vpn:/etc/zabbix/scripts# /usr/local/vpnserver/vpncmd
> > vpncmd command - SoftEther VPN Command Line Management Utility
> > SoftEther VPN Command Line Management Utility (vpncmd command)
> > Version 4.43 Build 9799   (English)
> > Compiled 2023/08/31 10:50:49 by buildsan at crosswin with OpenSSL 3.0.9
> 
> спасибо, попробую воспроизвести у себя

Благодарю! Очень хочется мониторинга)

**Comment by nickdsl** [comment]
> > > Версии такие:
> > > root@vpn:/etc/zabbix/scripts# python3 --version
> > > Python 3.9.2
> > > root@vpn:/etc/zabbix/scripts# lsb_release -a
> > > No LSB modules are available.
> > > Distributor ID: Debian
> > > Description:    Debian GNU/Linux 11 (bullseye)
> > > Release:        11
> > > Codename:       bullseye
> > > root@vpn:/etc/zabbix/scripts# /usr/local/vpnserver/vpncmd
> > > vpncmd command - SoftEther VPN Command Line Management Utility
> > > SoftEther VPN Command Line Management Utility (vpncmd command)
> > > Version 4.43 Build 9799   (English)
> > > Compiled 2023/08/31 10:50:49 by buildsan at crosswin with OpenSSL 3.0.9
> > 
> > спасибо, попробую воспроизвести у себя
> 
> Благодарю! Очень хочется мониторинга)

root@debsrv01:/etc/zabbix/scripts# zabbix_agent2 -t sevpn[hub.discovery]
sevpn[hub.discovery]                          [s|{"data": [{"{#HUBNAME}": "HUB_BIBA", "{#ONLINE}": 1, "{#TYPE}": 0, "{#TRAFFICFILLED}": 1}]}]

я развернул дебиан 11, обновил ее.
установил sevpn этой же версии что и у вас. 
результат приведен выше . у меня все работает .

**Comment by nickdsl** [comment]
> > > Версии такие:
> > > root@vpn:/etc/zabbix/scripts# python3 --version
> > > Python 3.9.2
> > > root@vpn:/etc/zabbix/scripts# lsb_release -a
> > > No LSB modules are available.
> > > Distributor ID: Debian
> > > Description:    Debian GNU/Linux 11 (bullseye)
> > > Release:        11
> > > Codename:       bullseye
> > > root@vpn:/etc/zabbix/scripts# /usr/local/vpnserver/vpncmd
> > > vpncmd command - SoftEther VPN Command Line Management Utility
> > > SoftEther VPN Command Line Management Utility (vpncmd command)
> > > Version 4.43 Build 9799   (English)
> > > Compiled 2023/08/31 10:50:49 by buildsan at crosswin with OpenSSL 3.0.9
> > 
> > спасибо, попробую воспроизвести у себя
> 
> Благодарю! Очень хочется мониторинга)

возможно я знаю причину.
Я подозреваю, что Вы указали неверный пароль в файле /etc/zabbix/scripts/sevpn.ini

**Comment by zakharov69** [comment]
> > > > Версии такие:
> > > > root@vpn:/etc/zabbix/scripts# python3 --version
> > > > Python 3.9.2
> > > > root@vpn:/etc/zabbix/scripts# lsb_release -a
> > > > No LSB modules are available.
> > > > Distributor ID: Debian
> > > > Description:    Debian GNU/Linux 11 (bullseye)
> > > > Release:        11
> > > > Codename:       bullseye
> > > > root@vpn:/etc/zabbix/scripts# /usr/local/vpnserver/vpncmd
> > > > vpncmd command - SoftEther VPN Command Line Management Utility
> > > > SoftEther VPN Command Line Management Utility (vpncmd command)
> > > > Version 4.43 Build 9799   (English)
> > > > Compiled 2023/08/31 10:50:49 by buildsan at crosswin with OpenSSL 3.0.9
> > > 
> > > 
> > > спасибо, попробую воспроизвести у себя
> > 
> > 
> > Благодарю! Очень хочется мониторинга)
> 
> возможно я знаю причину. Я подозреваю, что Вы указали неверный пароль в файле /etc/zabbix/scripts/sevpn.ini

Эх, я бы с радостью ошибся в нем) Может быть прав не хватает на выполнение? У sevpn.py владелец и группа zabbix должны быть?

**Comment by nickdsl** [comment]
> > > > > Версии такие:
> > > > > root@vpn:/etc/zabbix/scripts# python3 --version
> > > > > Python 3.9.2
> > > > > root@vpn:/etc/zabbix/scripts# lsb_release -a
> > > > > No LSB modules are available.
> > > > > Distributor ID: Debian
> > > > > Description:    Debian GNU/Linux 11 (bullseye)
> > > > > Release:        11
> > > > > Codename:       bullseye
> > > > > root@vpn:/etc/zabbix/scripts# /usr/local/vpnserver/vpncmd
> > > > > vpncmd command - SoftEther VPN Command Line Management Utility
> > > > > SoftEther VPN Command Line Management Utility (vpncmd command)
> > > > > Version 4.43 Build 9799   (English)
> > > > > Compiled 2023/08/31 10:50:49 by buildsan at crosswin with OpenSSL 3.0.9
> > > > 
> > > > 
> > > > спасибо, попробую воспроизвести у себя
> > > 
> > > 
> > > Благодарю! Очень хочется мониторинга)
> > 
> > 
> > возможно я знаю причину. Я подозреваю, что Вы указали неверный пароль в файле /etc/zabbix/scripts/sevpn.ini
> 
> Эх, я бы с радостью ошибся в нем) Может быть прав не хватает на выполнение? У sevpn.py владелец и группа zabbix должны быть?

Нет. Я вообще ничего не указывал такого.
Никаких доп настроек.
Просто скопировал файлы по scp из локальной репки с компа на виртуалку. Разложил файлы таким образом:

/etc/zabbix/scripts
- sevpn.ini
- sevpn.py
/etc/zabbix/zabbix_agent2.d/
- sevpn.conf

рестарт агента.
Первый агент или второй это вообще не важно.
Никаких доп библиотек питона не ставил. Все завелось из коробки.

Если там нет никакой секретной инфы, то можете скинуть мне конфиг своего sevpn.
Возможно у Вас там создано чего то такое, что как то аффектит скрипт (мало ли).

**Comment by nickdsl** [comment]
Ну, а вообще у меня есть желание переписать этот мониторинг. Я его писал давно, быстро, на коленке. Больше для себя чем для кого то. Оттого он сыпется трейсами если что то не так. Сейчас я понимаю, что могу написать его уже в парадигме ООП. Т.к. тут есть взаимодествие с API, то лучше это описать в виде класса со списком методов. Если будет пара-тройка свободных часов, то думаю на этой неделе запушу сюда новую версию. По крайней мере она будет говорить что именно с ней не так.

**Comment by zakharov69** [comment]
> > > > > > Версии такие:
> > > > > > root@vpn:/etc/zabbix/scripts# python3 --version
> > > > > > Python 3.9.2
> > > > > > root@vpn:/etc/zabbix/scripts# lsb_release -a
> > > > > > No LSB modules are available.
> > > > > > Distributor ID: Debian
> > > > > > Description:    Debian GNU/Linux 11 (bullseye)
> > > > > > Release:        11
> > > > > > Codename:       bullseye
> > > > > > root@vpn:/etc/zabbix/scripts# /usr/local/vpnserver/vpncmd
> > > > > > vpncmd command - SoftEther VPN Command Line Management Utility
> > > > > > SoftEther VPN Command Line Management Utility (vpncmd command)
> > > > > > Version 4.43 Build 9799   (English)
> > > > > > Compiled 2023/08/31 10:50:49 by buildsan at crosswin with OpenSSL 3.0.9
> > > > > 
> > > > > 
> > > > > спасибо, попробую воспроизвести у себя
> > > > 
> > > > 
> > > > Благодарю! Очень хочется мониторинга)
> > > 
> > > 
> > > возможно я знаю причину. Я подозреваю, что Вы указали неверный пароль в файле /etc/zabbix/scripts/sevpn.ini
> > 
> > 
> > Эх, я бы с радостью ошибся в нем) Может быть прав не хватает на выполнение? У sevpn.py владелец и группа zabbix должны быть?
> 
> Нет. Я вообще ничего не указывал такого. Никаких доп настроек. Просто скопировал файлы по scp из локальной репки с компа на виртуалку. Разложил файлы таким образом:
> 
> /etc/zabbix/scripts
> 
> * sevpn.ini
> * sevpn.py
>   /etc/zabbix/zabbix_agent2.d/
> * sevpn.conf
> 
> рестарт агента. Первый агент или второй это вообще не важно. Никаких доп библиотек питона не ставил. Все завелось из коробки.
> 
> Если там нет никакой секретной инфы, то можете скинуть мне конфиг своего sevpn. Возможно у Вас там создано чего то такое, что как то аффектит скрипт (мало ли).

https://dropmefiles.com/IlPi4 пароль: tc7WUk

**Comment by nickdsl** [comment]
> > > > > > > Версии такие:
> > > > > > > root@vpn:/etc/zabbix/scripts# python3 --version
> > > > > > > Python 3.9.2
> > > > > > > root@vpn:/etc/zabbix/scripts# lsb_release -a
> > > > > > > No LSB modules are available.
> > > > > > > Distributor ID: Debian
> > > > > > > Description:    Debian GNU/Linux 11 (bullseye)
> > > > > > > Release:        11
> > > > > > > Codename:       bullseye
> > > > > > > root@vpn:/etc/zabbix/scripts# /usr/local/vpnserver/vpncmd
> > > > > > > vpncmd command - SoftEther VPN Command Line Management Utility
> > > > > > > SoftEther VPN Command Line Management Utility (vpncmd command)
> > > > > > > Version 4.43 Build 9799   (English)
> > > > > > > Compiled 2023/08/31 10:50:49 by buildsan at crosswin with OpenSSL 3.0.9
> > > > > > 
> > > > > > 
> > > > > > спасибо, попробую воспроизвести у себя
> > > > > 
> > > > > 
> > > > > Благодарю! Очень хочется мониторинга)
> > > > 
> > > > 
> > > > возможно я знаю причину. Я подозреваю, что Вы указали неверный пароль в файле /etc/zabbix/scripts/sevpn.ini
> > > 
> > > 
> > > Эх, я бы с радостью ошибся в нем) Может быть прав не хватает на выполнение? У sevpn.py владелец и группа zabbix должны быть?
> > 
> > Нет. Я вообще ничего не указывал такого. Никаких доп настроек. Просто скопировал файлы по scp из локальной репки с компа на виртуалку. Разложил файлы таким образом:
> > 
> > /etc/zabbix/scripts
> > 
> > * sevpn.ini
> > * sevpn.py
> >   /etc/zabbix/zabbix_agent2.d/
> > * sevpn.conf
> > 
> > рестарт агента. Первый агент или второй это вообще не важно. Никаких доп библиотек питона не ставил. Все завелось из коробки.
> > 
> > Если там нет никакой секретной инфы, то можете скинуть мне конфиг своего sevpn. Возможно у Вас там создано чего то такое, что как то аффектит скрипт (мало ли).
> 
> https://dropmefiles.com/IlPi4 пароль: tc7WUk

ок. немного позже гляну

**Comment by nickdsl** [comment]
> > > > > > > Версии такие:
> > > > > > > root@vpn:/etc/zabbix/scripts# python3 --version
> > > > > > > Python 3.9.2
> > > > > > > root@vpn:/etc/zabbix/scripts# lsb_release -a
> > > > > > > No LSB modules are available.
> > > > > > > Distributor ID: Debian
> > > > > > > Description:    Debian GNU/Linux 11 (bullseye)
> > > > > > > Release:        11
> > > > > > > Codename:       bullseye
> > > > > > > root@vpn:/etc/zabbix/scripts# /usr/local/vpnserver/vpncmd
> > > > > > > vpncmd command - SoftEther VPN Command Line Management Utility
> > > > > > > SoftEther VPN Command Line Management Utility (vpncmd command)
> > > > > > > Version 4.43 Build 9799   (English)
> > > > > > > Compiled 2023/08/31 10:50:49 by buildsan at crosswin with OpenSSL 3.0.9
> > > > > > 
> > > > > > 
> > > > > > спасибо, попробую воспроизвести у себя
> > > > > 
> > > > > 
> > > > > Благодарю! Очень хочется мониторинга)
> > > > 
> > > > 
> > > > возможно я знаю причину. Я подозреваю, что Вы указали неверный пароль в файле /etc/zabbix/scripts/sevpn.ini
> > > 
> > > 
> > > Эх, я бы с радостью ошибся в нем) Может быть прав не хватает на выполнение? У sevpn.py владелец и группа zabbix должны быть?
> > 
> > 
> > Нет. Я вообще ничего не указывал такого. Никаких доп настроек. Просто скопировал файлы по scp из локальной репки с компа на виртуалку. Разложил файлы таким образом:
> > /etc/zabbix/scripts
> > 
> > * sevpn.ini
> > * sevpn.py
> >   /etc/zabbix/zabbix_agent2.d/
> > * sevpn.conf
> > 
> > рестарт агента. Первый агент или второй это вообще не важно. Никаких доп библиотек питона не ставил. Все завелось из коробки.
> > Если там нет никакой секретной инфы, то можете скинуть мне конфиг своего sevpn. Возможно у Вас там создано чего то такое, что как то аффектит скрипт (мало ли).
> 
> https://dropmefiles.com/IlPi4 пароль: tc7WUk

Попробуйте скачать свежую версию мониторинга. Я закоммитил изменения.
Там новая версия шаблона и новый Python-код.
Написал инструкцию.

Также крайне рекомендую  вот этот параметр в Вашем конфиге "bool DisableJsonRpcWebApi true" установить в false.
Хотя бы потому, что он блокирует API. Следовательно мониторинг работать тоже не может. Если не выключить данный параметр мониторить Sevpn возможно только через vpncmd, а это основываясь на моем прошлом опыте более ресурсоемкое занятия. Чем больше сущностей заведено в Sevpn (хабы, пользователи, каскады и тп.), тем больше cpu будет съедать мониоринг на vpncmd. Это собственно была одна из причин почему я в свое время решил переписать bash-скрипт мониторинга через vpncmd, на python-скрипт и API.

**Comment by zakharov69** [comment]
Благодарю! В понедельник обязательно запущу!

Получите Outlook для Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by nickdsl** [comment]
> Благодарю! В понедельник обязательно запущу! Получите Outlook для Android<https://aka.ms/AAb9ysg>

Получилось?

**Comment by zakharov69** [comment]
> > Благодарю! В понедельник обязательно запущу! Получите Outlook для Androidhttps://aka.ms/AAb9ysg
> 
> Получилось?

Стало что-то появляться
![image](https://github.com/nickdsl/sevpn_zabbix/assets/33763339/47fc144f-6be3-4a8d-918a-7a69090d45ff)

При входе на сервер по адресу https://vpn.servers.local:5555/api/ выскакивает окно с запросом логина и пароля. Так и должно быть?
![image](https://github.com/nickdsl/sevpn_zabbix/assets/33763339/f82a3754-d063-4099-ac1b-49822f8262d0)

Примеры запросов из командной строки:
![image](https://github.com/nickdsl/sevpn_zabbix/assets/33763339/65be74d8-c9f8-4edf-a793-1df302f28afc)

Видимо у меня что-то не так?
![image](https://github.com/nickdsl/sevpn_zabbix/assets/33763339/00dd77e4-8077-408e-b6cb-d69a3313fce1)

**Comment by nickdsl** [comment]
> При входе на сервер по адресу https://vpn.servers.local:5555/api/ выскакивает окно с запросом логина и пароля. Так и должно быть? 
Да, это приглашение API для авторизации.

Я посмотрел вывод. Видимо есть какие то шероховатости в коде.
Но на моих прод впн такого я не встретил. 
Попробую поставить Ваш конфиг на мониторинг у себя локально и отдебажить проблемы. Думаю сегодня будет какой то результат.

**Comment by nickdsl** [comment]
@zakharov69 
root@debsrv02:~# sudo -u zabbix zabbix_agent2 -t sevpn[server.info]
`sudo: unable to resolve host debsrv02: Неизвестное имя или служба
sevpn[server.info]                            [s|{"data": {"result": {"KernelName_str": "Linux Kernel", "OsProductName_str": "Linux", "OsServicePack_u32": 0, "OsSystemName_str": "Linux", "OsType_u32": 3100, "OsVendorName_str": "Unknown Vendor", "OsVersion_str": "Unknown Linux Version", "ServerBuildDate_dt": "2023-08-31T10:50:49.000Z", "ServerBuildInfoString_str": "Compiled 2023/08/31 10:50:49 by buildsan at crosswin with OpenSSL 3.0.9", "ServerBuildInt_u32": 9799, "ServerFamilyName_str": "SoftEther", "ServerHostName_str": "debsrv02", "ServerProductName_str": "SoftEther VPN Server (64 bit)", "ServerType_u32": 0, "ServerVerInt_u32": 443, "ServerVersionString_str": "Version 4.43 Build 9799   (English)"}, "jsonrpc": "2.0", "id": "rpc_call_id"}, "error": ""}]`

root@debsrv02:~# sudo -u zabbix zabbix_agent2 -t sevpn[server.status]
`sudo: unable to resolve host debsrv02: Неизвестное имя или служба
sevpn[server.status]                          [s|{"data": {"result": {"AssignedBridgeLicenses_u32": 0, "AssignedBridgeLicensesTotal_u32": 0, "AssignedClientLicenses_u32": 0, "AssignedClientLicensesTotal_u32": 0, "CurrentTick_u64": 505677, "CurrentTime_dt": "2023-12-19T06:37:22.086Z", "FreeMemory_u64": 0, "FreePhys_u64": 0, "NumGroups_u32": 23, "NumHubDynamic_u32": 0, "NumHubStandalone_u32": 12, "NumHubStatic_u32": 0, "NumHubTotal_u32": 12, "NumIpTables_u32": 1, "NumMacTables_u32": 1, "NumSessionsLocal_u32": 0, "NumSessionsRemote_u32": 0, "NumSessionsTotal_u32": 0, "NumTcpConnections_u32": 95, "NumTcpConnectionsLocal_u32": 95, "NumTcpConnectionsRemote_u32": 0, "NumUsers_u32": 388, "Recv.BroadcastBytes_u64": 61716081059, "Recv.BroadcastCount_u64": 627266828, "Recv.UnicastBytes_u64": 4298817857132, "Recv.UnicastCount_u64": 11978628242, "Send.BroadcastBytes_u64": 60166957435, "Send.BroadcastCount_u64": 619107653, "Send.UnicastBytes_u64": 3094553044674, "Send.UnicastCount_u64": 7436718504, "ServerType_u32": 0, "StartTime_dt": "2023-12-19T06:28:56.445Z", "TotalMemory_u64": 0, "TotalPhys_u64": 0, "UsedMemory_u64": 0, "UsedPhys_u64": 0, "zabbix_uptime": 506}, "jsonrpc": "2.0", "id": "rpc_call_id"}, "error": ""}]`

root@debsrv02:~# sudo -u zabbix zabbix_agent2 -t sevpn[listener.discovery]
`sudo: unable to resolve host debsrv02: Неизвестное имя или служба
sevpn[listener.discovery]                     [s|{"data": [{"{#PORT}": 443, "{#ENABLED}": 1}, {"{#PORT}": 1194, "{#ENABLED}": 1}, {"{#PORT}": 5555, "{#ENABLED}": 1}]}]`

У меня все запросы из командной строки отдают корректный результат на тестовой Debian 11 на SeVPN той же версии что и у Вас, и на том же конфиге.

Если у Вас есть желание/возможность, то я мог бы удаленно взглянуть (Anydesk + открытый терминал) конкретно на Ваш сервер и попытаться понять почему именно в Вашем случае ничего не работает.

**Comment by zakharov69** [comment]
> @zakharov69 root@debsrv02:~# sudo -u zabbix zabbix_agent2 -t sevpn[server.info] `sudo: unable to resolve host debsrv02: Неизвестное имя или служба sevpn[server.info] [s|{"data": {"result": {"KernelName_str": "Linux Kernel", "OsProductName_str": "Linux", "OsServicePack_u32": 0, "OsSystemName_str": "Linux", "OsType_u32": 3100, "OsVendorName_str": "Unknown Vendor", "OsVersion_str": "Unknown Linux Version", "ServerBuildDate_dt": "2023-08-31T10:50:49.000Z", "ServerBuildInfoString_str": "Compiled 2023/08/31 10:50:49 by buildsan at crosswin with OpenSSL 3.0.9", "ServerBuildInt_u32": 9799, "ServerFamilyName_str": "SoftEther", "ServerHostName_str": "debsrv02", "ServerProductName_str": "SoftEther VPN Server (64 bit)", "ServerType_u32": 0, "ServerVerInt_u32": 443, "ServerVersionString_str": "Version 4.43 Build 9799 (English)"}, "jsonrpc": "2.0", "id": "rpc_call_id"}, "error": ""}]`
> 
> root@debsrv02:~# sudo -u zabbix zabbix_agent2 -t sevpn[server.status] `sudo: unable to resolve host debsrv02: Неизвестное имя или служба sevpn[server.status] [s|{"data": {"result": {"AssignedBridgeLicenses_u32": 0, "AssignedBridgeLicensesTotal_u32": 0, "AssignedClientLicenses_u32": 0, "AssignedClientLicensesTotal_u32": 0, "CurrentTick_u64": 505677, "CurrentTime_dt": "2023-12-19T06:37:22.086Z", "FreeMemory_u64": 0, "FreePhys_u64": 0, "NumGroups_u32": 23, "NumHubDynamic_u32": 0, "NumHubStandalone_u32": 12, "NumHubStatic_u32": 0, "NumHubTotal_u32": 12, "NumIpTables_u32": 1, "NumMacTables_u32": 1, "NumSessionsLocal_u32": 0, "NumSessionsRemote_u32": 0, "NumSessionsTotal_u32": 0, "NumTcpConnections_u32": 95, "NumTcpConnectionsLocal_u32": 95, "NumTcpConnectionsRemote_u32": 0, "NumUsers_u32": 388, "Recv.BroadcastBytes_u64": 61716081059, "Recv.BroadcastCount_u64": 627266828, "Recv.UnicastBytes_u64": 4298817857132, "Recv.UnicastCount_u64": 11978628242, "Send.BroadcastBytes_u64": 60166957435, "Send.BroadcastCount_u64": 619107653, "Send.UnicastBytes_u64": 3094553044674, "Send.UnicastCount_u64": 7436718504, "ServerType_u32": 0, "StartTime_dt": "2023-12-19T06:28:56.445Z", "TotalMemory_u64": 0, "TotalPhys_u64": 0, "UsedMemory_u64": 0, "UsedPhys_u64": 0, "zabbix_uptime": 506}, "jsonrpc": "2.0", "id": "rpc_call_id"}, "error": ""}]`
> 
> root@debsrv02:~# sudo -u zabbix zabbix_agent2 -t sevpn[listener.discovery] `sudo: unable to resolve host debsrv02: Неизвестное имя или служба sevpn[listener.discovery] [s|{"data": [{"{#PORT}": 443, "{#ENABLED}": 1}, {"{#PORT}": 1194, "{#ENABLED}": 1}, {"{#PORT}": 5555, "{#ENABLED}": 1}]}]`
> 
> У меня все запросы из командной строки отдают корректный результат на тестовой Debian 11 на SeVPN той же версии что и у Вас, и на том же конфиге.
> 
> Если у Вас есть желание/возможность, то я мог бы удаленно взглянуть (Anydesk + открытый терминал) конкретно на Ваш сервер и попытаться понять почему именно в Вашем случае ничего не работает.

Да без проблем, только VPN-сервер сейчас нельзя перезагружать, а то рабочий день, людей много работает
Anydesk 1695843823

**Comment by nickdsl** [comment]
> Да без проблем, только VPN-сервер сейчас нельзя перезагружать, а то рабочий день, людей много работает
> Anydesk 1695843823

ещё актуально ? есть возможность сейчас ну или в ближайшее время?

**Comment by nickdsl** [comment]
> Да без проблем, только VPN-сервер сейчас нельзя перезагружать, а то рабочий день, людей много работает Anydesk 1695843823

Посмотрим? Есть время?

**Comment by zakharov69** [comment]
> > Да без проблем, только VPN-сервер сейчас нельзя перезагружать, а то рабочий день, людей много работает Anydesk 1695843823
> 
> Посмотрим? Есть время?

Давайте! Anydesk 1695843823

**Comment by nickdsl** [comment]
> Давайте! Anydesk 1695843823

1) Забыл подчистить за собой.
Нужно удалить файлы: /etc/zabbix/scripts/sevpn2.py и /etc/zabbix/scripts/sevpn_zabbix2.py т.к. они носят тестовый характер.

2) Тем не  менее увидел места, где нужно допилить код, чтобы он не вываливался в ошибку, а доносил информацию в виде триггера во фронтэнд. Как только все будет готово выложу сюда в репозиторий. По факту будут обновлены какие то из файлов: sevpn.py , sevpn_zabbix.py, sevpn_api.py. Изменения не поломают текущий мониторинг, можно смело заменять их новыми версиями.

**Comment by zakharov69** [comment]
> > Давайте! Anydesk 1695843823
> 
> 1. Забыл подчистить за собой.
>    Нужно удалить файлы: /etc/zabbix/scripts/sevpn2.py и /etc/zabbix/scripts/sevpn_zabbix2.py т.к. они носят тестовый характер.
> 2. Тем не  менее увидел места, где нужно допилить код, чтобы он не вываливался в ошибку, а доносил информацию в виде триггера во фронтэнд. Как только все будет готово выложу сюда в репозиторий. По факту будут обновлены какие то из файлов: sevpn.py , sevpn_zabbix.py, sevpn_api.py. Изменения не поломают текущий мониторинг, можно смело заменять их новыми версиями.

Благодарю! Разработчику респект и "+" в карму)
